### ISSUE TITLE
client_payload is too large

### ISSUE THREAD

**Issue by clxmstaab** [peter-evans/slash-command-dispatch#67] opened 2020-07-02 12:00 UTC
we did not change the workflow for a few days, but recently we see errors in the dispatching workflow:

![image](https://user-images.githubusercontent.com/47448731/86356213-261ac580-bc6c-11ea-9bd7-136ddd503ff2.png)

the workflow file is:
```
name: Chatops

on:
  issue_comment:
    types: [created]

jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.STAABM_TOKEN }}
          # reactions should be reported from github itself
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: help, csfix, phpstan-baseline, churn
          issue-type: pull-request
```

is there anything we can do on our end, or can be done on slash-command-dispatch to fix this problem?
maybe its even a problem triggerd by the GithubAction's infrastructure/runtime?

**Comment by peter-evans** [comment] 2020-07-03 13:28
Hi @clxmstaab 

I’ve tested a couple of my slash command workflows and I’m not able to reproduce this error. I wonder if the size of the `pull_request` context differs considerably depending on its content. I will investigate further to try and reproduce this. Let me know if you figure out anything that could help me narrow this down.

**Comment by peter-evans** [comment] 2020-07-05 07:28
@clxmstaab I've identified the fields of the different contexts passed in the payload that could vary in size and maybe cause this error.

`client_payload.github` contains the `issue_comment` context. This contains information about the issue that the slash command comment was made in. The JSON context has two array fields that could grow in size.
- `assignees`
- `labels`

`client_payload.pull_request` contains the payload from a GET request to `pulls/:pull_number`. This is only added to the payload if the slash command was sent from a pull request, rather than a regular issue. This JSON payload contains four array fields that could grow in size.
- `assignees`
- `labels`
- `requested_reviewers`
- `requested_teams`

So if the pull request that you sent the slash command from has many of the above, it could potentially hit some limit for the size of the `client_payload`. Could you let me know how many `assignees`, `labels`, `requested_reviewers` and/or `requested_teams` the pull request had where the slash command failed.

**Comment by clxmstaab** [comment] 2020-07-13 09:38
I am back from vacation - thx for your investigation. I will check with the reporting developers and get back to you.

**Comment by clxmstaab** [comment] 2020-07-14 07:42
> So if the pull request that you sent the slash command from has many of the above, it could potentially hit some limit for the size of the `client_payload`. Could you let me know how many `assignees`, `labels`, `requested_reviewers` and/or `requested_teams` the pull request had where the slash command failed.

we had the problem on PRs which have
- 0 reviewers
- 0 assignees
- 3 labels
- no milestone
- no linked issue

the comment itself to trigger the command was just `/csfix` no additional text.

**Comment by clxmstaab** [comment] 2020-07-14 07:49
I was just able to reproduce the problem. I will try to debug it using: https://github.com/peter-evans/slash-command-dispatch#github-and-pull_request-contexts

**Comment by clxmstaab** [comment] 2020-07-14 07:57
my debug-workflow now looks like:
```
# DONT EDIT THIS FILE OUTSIDE OF complex-gmbh/php-automation-templates
# changes will be one-way synced from the automation repos

name: Chatops

on:
  issue_comment:
    types: [created]

jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.STAABM_TOKEN }}
          # reactions should be reported from github itself
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: help, csfix, phpstan-baseline, churn
          issue-type: pull-request
```

the raw output of the action run is

```
2020-07-14T07:52:37.7473921Z ##[section]Starting: Request a runner to run this job
2020-07-14T07:52:38.2985541Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'ubuntu-latest'
2020-07-14T07:52:38.2985587Z Can't find any online and idle self-hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2020-07-14T07:52:38.2985634Z Found online and idle hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2020-07-14T07:52:38.4992836Z ##[section]Finishing: Request a runner to run this job
2020-07-14T07:52:47.6466698Z Current runner version: '2.267.1'
2020-07-14T07:52:47.6471531Z Prepare workflow directory
2020-07-14T07:52:47.6690772Z Prepare all required actions
2020-07-14T07:52:47.6704307Z Download action repository 'peter-evans/slash-command-dispatch@v1'
2020-07-14T07:52:50.1722975Z ##[group]Run echo "$PAYLOAD_CONTEXT"
2020-07-14T07:52:50.1723518Z [36;1mecho "$PAYLOAD_CONTEXT"[0m
2020-07-14T07:52:50.1763896Z shell: /bin/bash -e {0}
2020-07-14T07:52:50.1764265Z env:
2020-07-14T07:52:50.1764411Z   PAYLOAD_CONTEXT: null
2020-07-14T07:52:50.1764593Z ##[endgroup]
2020-07-14T07:52:50.1882436Z null
2020-07-14T07:52:50.1948384Z ##[group]Run peter-evans/slash-command-dispatch@v1
2020-07-14T07:52:50.1948794Z with:
2020-07-14T07:52:50.1949104Z   token: ***
2020-07-14T07:52:50.1949488Z   reaction-token: ***
2020-07-14T07:52:50.1949693Z   commands: help, csfix, phpstan-baseline, churn
2020-07-14T07:52:50.1949881Z   issue-type: pull-request
2020-07-14T07:52:50.1950121Z ##[endgroup]
2020-07-14T07:52:51.1153507Z Using configuration from yaml inputs.
2020-07-14T07:52:51.2933376Z Command 'csfix' to be dispatched.
2020-07-14T07:52:52.6205228Z ##[error]client_payload is too large.
2020-07-14T07:52:52.6249996Z Cleaning up orphan processes
```

its seems the payload is NULL but still too large?

I reproduced the issue with adding a comment to a PR which was already merged and the branch was already removed.
adding the comment there does not make much sense at this time, but as it reproduces a maybe similar problem I figured it could still be usefull for debugging purposes.

**Comment by peter-evans** [comment] 2020-07-15 02:03
Um, just three labels doesn't seem enough to create a very large payload. There must be something else going on here.

You can't debug the `client_payload` from a step in that workflow because it is constructed and sent during the action step.

I've create a release called `v1-debug` and added a [debug output for the client payload](https://github.com/peter-evans/slash-command-dispatch/blob/v1-debug/src/index.js#L162). Please could you try this release and capture the debug output when the error occurs. In your workflow, simply change `peter-evans/slash-command-dispatch@v1` to `peter-evans/slash-command-dispatch@v1-debug`, and set a secret in the repository where the workflow runs `ACTIONS_STEP_DEBUG` = `true`. That will allow debug output to appear in the logs.

**Comment by clxmstaab** [comment] 2020-07-16 07:34
thx for your investigation.

I put everything up like you suggested and the action, which still errors, produces the following log:

https://gist.github.com/clxmstaab/402628b973950948984e2ccb403e75b5

@peter-evans please let me know when you copied the gist for yourself, so I can delete it again. I want to delete it as fast as possible, just to be sure there is no sensitive data in there.

**Comment by peter-evans** [comment] 2020-07-16 07:47
@clxmstaab Saved the log. Thank you. I will investigate further.

**Comment by peter-evans** [comment] 2020-07-16 08:47
@clxmstaab The problem is clear now, but fixing it could be tricky. I need to reduce the size of the `client_payload`, but I can't remove properties of the payload from the current `v1` version of the action because it might break user's workflows. I need some time to think about how to implement it and roll it out as `v2`.

In the meantime, I want to find a temporary fix for you. The `client_payload` is large in your case because the pull request `body` has a lot of content. I'm assuming that you aren't reading the `body` property of the payload, so I've made a temporary release to remove those properties from the payload. Please try using `peter-evans/slash-command-dispatch@v1-payload-fix` for now, until I can implement a long-term solution.

**Comment by clxmstaab** [comment] 2020-07-16 09:15
> Please try using `peter-evans/slash-command-dispatch@v1-payload-fix` for now, until I can implement a long-term solution.

confirmed, the fix. with this version the problem is gone.

**Comment by peter-evans** [comment] 2020-07-23 03:38
@clxmstaab I'm now testing `v2` of this action which is being developed in the `dev` branch and currently tagged as `v2-beta`. It includes a fix for this issue. It would be great to get your feedback if you have time to test it. 

```
uses: peter-evans/slash-command-dispatch@v2-beta
```

See the full change notes here: https://github.com/peter-evans/slash-command-dispatch/blob/dev/docs/updating.md#updating-from-v1-to-v2

**Comment by clxmstaab** [comment] 2020-07-23 10:02
just added some notes on the relevant commits

**Comment by peter-evans** [comment] 2020-07-24 02:59
Thanks. It was useful feedback.

**Closed** 2020-07-25 04:03 UTC

**Comment by martinm82** [comment] 2025-07-09 12:11
Hi all,
unfortunately I hit now the same issue. My PRs have quite big descriptions and even though the body of the PR description is truncated in the code it seems to be not sufficient. 
I am running the action in debug mode and I only see part of the body content. At the end the debug output says `...59551 more characters,`

Our repos have some `custom_properties` assigned and I am wondering whether all this stuff needs to be in the payload. If one wants to get some special information it can always be done through the REST API and some basic info like repo and PR number. This information should be actually enough, or am I wrong?

I know that some users of the current version could rely on the content of the current `client_payload` and removing attributes would break their integrations.
